### ISSUE TITLE
Heading containing __ is broken

### ISSUE THREAD

**Issue by arikon** [veged/shmakowiki#14]
Escaping with ~ doesn't help.

Example: `b-form-input__hint`

**Comment by arikon** [comment]
Could not reproduce

**Comment by tadatuta** [comment]
the way to reprosuce:
1. Content of the blocks-desktop/b-hint-input/b-hint-input.title.txt:
Подсказка для поля ввода (deprecated, будет удалено в 2.10, используйте b-form-input~__hint)
2. Build: make blocks-desktop/b-hint-input/b-hint-input.wiki.xml -B
3. The result:

<h1 class="b-wiki-content__title"><span>b-hint-input</span>: Подсказка для поля ввода (deprecated, будет удалено в 2.10, используйте b-form-input</h1>
