### ISSUE TITLE
Возможность задать якорь для заголовка

### ISSUE THREAD

**Issue by vithar** [veged/shmakowiki#6]
Я предлагаю

===(anchor) Текст заголовка

**Comment by veged** [comment]
я за то, чтобы делать так
    === Заголовок == zagolovok
вся часть со второй последовательности для заголовка (включая её саму) опциональна

плюс ещё можно делать автоякоря из транслитерации

**Comment by vithar** [comment]
Может так:

=== Заголовок #zagolovok1

?

Что-то мне == кажются нелогичными. Можешь объяснить ход мыслей?

**Comment by veged** [comment]
`==` это использование уже существующего элемента разметки, он в заголовках есть уже сейчас

использовать # как есть нельзя, это слишком опасно "ложными срабатываниями", ## уже занято, ну и т.д. и т.п.

**Comment by vithar** [comment]
В лего сейчас так сделано для заголовков

===== С двумя полями ^^((#b-search.double §))^^

Если для ссылок можно не указывать текст, то задача решена.

**Comment by veged** [comment]
это ссылка, а мы обсуждаем якорь

**Comment by arikon** [comment]
Сделали же
